version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
    - db
    container_name: foodgram-back
    image: sainekt/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    container_name: foodgram-front
    image: sainekt/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    depends_on:
      - backend
      - frontend
    container_name: foodgram-proxy
    image: sainekt/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - media:/media
      - static:/static
