volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    container_name: foodgram-back
    env_file: ./.env
    build: ./backend
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - static:/static
  nginx:
    depends_on:
      - db
      - frontend
      - backend
    build: ./infra/
    env_file: ./.env
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - media:/media
      - static:/static
