# Generated by Django 5.1.1 on 2024-09-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество игридиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=1, max_length=10, verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
    ]
