# Generated by Django 5.1.1 on 2024-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientsrecipes_quantity_recipe_short_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsrecipes',
            old_name='quantity',
            new_name='amount',
        ),
    ]
